# Generated by Django 5.0 on 2023-12-12 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_created=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Task date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
