# Generated by Django 5.0 on 2023-12-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='color',
            field=models.CharField(default='#808080', max_length=100, verbose_name='Color'),
        ),
    ]
